name: Post Gatekeeping Notifications to Developer Repos

on:
  workflow_dispatch:
    inputs:
      dry_run:
        description: 'Dry run mode (no issues will be created)'
        required: false
        default: 'true'
        type: choice
        options:
          - 'true'
          - 'false'

jobs:
  post-notifications:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: main
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install PyGithub python-dotenv
      
      - name: Post notifications to developer repositories
        env:
          AWESOME_CC_PAT_PUBLIC_REPO: ${{ secrets.AWESOME_CC_PAT_PUBLIC_REPO }}
          DRY_RUN: ${{ github.event.inputs.dry_run }}
        run: |
          echo "Creating notification issues in developer repositories..."
          python3 scripts/post_notifications.py
      
      - name: Summary
        if: always()
        run: |
          echo "==================================="
          echo "Notification Posting Complete"
          echo "==================================="
          echo "Dry run: ${{ github.event.inputs.dry_run }}"
          echo "==================================="
